import pandas as pd
series1= pd.Series([56,57,58],index=['In1','In2','In3'])
series2= pd.Series([70,72,74,16],index=['In1','In2','In3','c++'])
table=pd.DataFrame({'Akp':series1,'PP':series2})
# print(table)
table['Pre']=pd.Series([40,41,42,43], index=['In1','In2','In3','c++'])
table=table.append(pd.DataFrame([[10,12,13]] , columns= ['Akp','PP','Pre']))
print(table)
table.to_csv('pandascsv.csv')
# print(table.iloc[3])
# jim=table.pop('Akp')
# print(jim)
# del(table['Akp'])
# print(table)
